[workspace]
resolver = "2"

members = [
    "crates/chartml-core",
    "crates/chartml-chart-cartesian",
    "crates/chartml-chart-pie",
    "crates/chartml-chart-scatter",
    "crates/chartml-chart-metric",
    "crates/chartml-forecast",
    "crates/chartml-datafusion",
    "crates/chartml-leptos",
    "crates/chartml-render",
    "crates/chartml-test-runner",
    "demo",
]

default-members = [
    "crates/chartml-core",
    "crates/chartml-chart-cartesian",
    "crates/chartml-chart-pie",
    "crates/chartml-chart-scatter",
    "crates/chartml-chart-metric",
    "crates/chartml-forecast",
    "crates/chartml-datafusion",
    "crates/chartml-render",
    "crates/chartml-test-runner",
]

# Optimize WASM release builds for size
[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true
