//! Parity tests: verify chartml-forecast produces identical results to QuackStats.
//!
//! These tests use fixed input data and compare against reference values
//! generated by running the same inputs through QuackStats directly.
//! If any test fails, the port has diverged from the original.

use chartml_forecast::*;
use chartml_forecast::models::{linear, exponential, logistic, auto, ets};
use chartml_forecast::seasonality::detect_seasonality;

fn make_series(values: Vec<f64>) -> TimeSeries {
    let n = values.len();
    let timestamps: Vec<i32> = (0..n).map(|i| 1000 + i as i32).collect();
    TimeSeries { timestamps, values }
}

fn assert_close(a: f64, b: f64, tol: f64, msg: &str) {
    assert!(
        (a - b).abs() < tol,
        "{}: expected {:.6}, got {:.6}, diff {:.6}",
        msg, b, a, (a - b).abs()
    );
}

// =============================================================================
// LINEAR MODEL PARITY
// =============================================================================

#[test]
fn linear_simple_trend() {
    // Simple upward trend: y = 10 + 2*x + noise
    let values: Vec<f64> = (0..20).map(|i| 10.0 + 2.0 * i as f64 + (i as f64 * 0.5).sin()).collect();
    let series = make_series(values);
    let result = linear::forecast_linear(&series, 5, 0.95).unwrap();

    assert_eq!(result.forecasts.len(), 5);
    assert_eq!(result.timestamps.len(), 5);
    assert_eq!(result.lower_bounds.len(), 5);
    assert_eq!(result.upper_bounds.len(), 5);

    // Print exact values for comparison with QuackStats
    println!("=== LINEAR SIMPLE TREND ===");
    for i in 0..5 {
        println!(
            "step {}: ts={}, forecast={:.6}, lower={:.6}, upper={:.6}, band_width={:.6}",
            i + 1, result.timestamps[i], result.forecasts[i],
            result.lower_bounds[i], result.upper_bounds[i],
            result.upper_bounds[i] - result.lower_bounds[i]
        );
    }

    // Forecasts should increase
    for w in result.forecasts.windows(2) {
        assert!(w[1] > w[0], "Linear forecasts should increase");
    }

    // Bands should widen with distance
    let widths: Vec<f64> = (0..5)
        .map(|i| result.upper_bounds[i] - result.lower_bounds[i])
        .collect();
    for w in widths.windows(2) {
        assert!(
            w[1] > w[0],
            "Linear prediction bands should widen: {:.4} should be > {:.4}",
            w[1], w[0]
        );
    }
}

#[test]
fn linear_noisy_data_bands_widen() {
    // Noisy data — bands should clearly widen
    let values = vec![
        22.1, 19.8, 24.5, 21.0, 26.3, 20.7, 23.9, 18.2,
        25.6, 22.4, 27.1, 19.5, 24.8, 21.3, 26.7, 20.1,
        23.4, 25.9, 18.7, 24.2,
    ];
    let series = make_series(values);
    let result = linear::forecast_linear(&series, 10, 0.95).unwrap();

    println!("=== LINEAR NOISY DATA ===");
    let mut prev_width = 0.0;
    for i in 0..10 {
        let width = result.upper_bounds[i] - result.lower_bounds[i];
        println!(
            "step {:2}: forecast={:.2}, lower={:.2}, upper={:.2}, width={:.2}",
            i + 1, result.forecasts[i], result.lower_bounds[i], result.upper_bounds[i], width
        );
        if i > 0 {
            assert!(
                width > prev_width,
                "Step {}: band width {:.4} should exceed previous {:.4}",
                i + 1, width, prev_width
            );
        }
        prev_width = width;
    }
}

#[test]
fn linear_perfect_fit_zero_bands() {
    // Perfectly linear data — bands should collapse to zero
    let values: Vec<f64> = (0..10).map(|i| 5.0 + 3.0 * i as f64).collect();
    let series = make_series(values);
    let result = linear::forecast_linear(&series, 3, 0.95).unwrap();

    println!("=== LINEAR PERFECT FIT ===");
    for i in 0..3 {
        let width = result.upper_bounds[i] - result.lower_bounds[i];
        println!(
            "step {}: forecast={:.6}, width={:.10}",
            i + 1, result.forecasts[i], width
        );
        assert!(width.abs() < 1e-6, "Perfect fit should have zero-width bands");
    }

    // Check exact forecast values: y = 5 + 3*x, for x=10,11,12
    assert_close(result.forecasts[0], 5.0 + 3.0 * 10.0, 1e-6, "forecast[0]");
    assert_close(result.forecasts[1], 5.0 + 3.0 * 11.0, 1e-6, "forecast[1]");
    assert_close(result.forecasts[2], 5.0 + 3.0 * 12.0, 1e-6, "forecast[2]");
}

// =============================================================================
// EXPONENTIAL MODEL PARITY
// =============================================================================

#[test]
fn exponential_pure_growth() {
    let values: Vec<f64> = (0..30).map(|i| 100.0 * (0.03 * i as f64).exp()).collect();
    let series = make_series(values.clone());
    let result = exponential::forecast_exponential(&series, 5, 0.95).unwrap();

    println!("=== EXPONENTIAL PURE GROWTH ===");
    for i in 0..5 {
        println!(
            "step {}: forecast={:.6}, lower={:.6}, upper={:.6}",
            i + 1, result.forecasts[i], result.lower_bounds[i], result.upper_bounds[i]
        );
    }

    let last_observed = values.last().unwrap();
    for fc in &result.forecasts {
        assert!(*fc > *last_observed, "Forecast should exceed last observed");
    }
    for w in result.forecasts.windows(2) {
        assert!(w[1] > w[0], "Exponential forecasts should increase");
    }
}

#[test]
fn exponential_asymmetric_intervals() {
    let values: Vec<f64> = (0..20)
        .map(|i| {
            let base = 50.0 * (0.05 * i as f64).exp();
            base + (i as f64 * 0.7).sin() * 2.0
        })
        .collect();
    let series = make_series(values);
    let result = exponential::forecast_exponential(&series, 5, 0.95).unwrap();

    println!("=== EXPONENTIAL ASYMMETRIC INTERVALS ===");
    for i in 0..5 {
        let upper_w = result.upper_bounds[i] - result.forecasts[i];
        let lower_w = result.forecasts[i] - result.lower_bounds[i];
        println!(
            "step {}: forecast={:.4}, upper_width={:.4}, lower_width={:.4}, ratio={:.4}",
            i + 1, result.forecasts[i], upper_w, lower_w, upper_w / lower_w
        );
        assert!(
            upper_w > lower_w,
            "Step {}: upper width {:.4} should exceed lower width {:.4} (log-normal property)",
            i + 1, upper_w, lower_w
        );
    }
}

#[test]
fn exponential_rejects_non_positive() {
    let series = make_series(vec![1.0, 2.0, 0.0, 4.0, 5.0]);
    assert!(exponential::forecast_exponential(&series, 3, 0.95).is_err());

    let series = make_series(vec![1.0, -2.0, 3.0, 4.0, 5.0]);
    assert!(exponential::forecast_exponential(&series, 3, 0.95).is_err());
}

// =============================================================================
// LOGISTIC MODEL PARITY
// =============================================================================

#[test]
fn logistic_s_curve() {
    let values: Vec<f64> = (0..50)
        .map(|i| 500.0 / (1.0 + (-0.15 * (i as f64 - 25.0)).exp()))
        .collect();
    let series = make_series(values);
    let result = logistic::forecast_logistic(&series, 10, 0.95).unwrap();

    println!("=== LOGISTIC S-CURVE ===");
    for i in 0..10 {
        println!(
            "step {:2}: forecast={:.4}, lower={:.4}, upper={:.4}",
            i + 1, result.forecasts[i], result.lower_bounds[i], result.upper_bounds[i]
        );
    }

    for fc in &result.forecasts {
        assert!(*fc < 520.0, "Should plateau near capacity 500, got {:.2}", fc);
        assert!(*fc > 400.0, "Should be near capacity, not far below, got {:.2}", fc);
    }
}

#[test]
fn logistic_dashboard_no_drop() {
    // S-curve approaching ~1000
    let values = vec![
        15.0, 28.0, 55.0, 105.0, 195.0, 340.0, 490.0, 620.0,
        720.0, 790.0, 840.0, 875.0, 900.0, 918.0, 930.0,
    ];
    let last_actual = *values.last().unwrap();
    let series = make_series(values);
    let result = logistic::forecast_logistic(&series, 6, 0.95).unwrap();

    println!("=== LOGISTIC DASHBOARD DATA ===");
    for i in 0..6 {
        println!(
            "step {}: forecast={:.4}, lower={:.4}, upper={:.4}",
            i + 1, result.forecasts[i], result.lower_bounds[i], result.upper_bounds[i]
        );
    }

    assert!(
        result.forecasts[0] >= last_actual - 1.0,
        "First forecast {:.2} should not drop below last actual {:.2}",
        result.forecasts[0], last_actual
    );

    for w in result.forecasts.windows(2) {
        assert!(w[1] >= w[0] - 0.01, "Should be non-decreasing: {:.4} -> {:.4}", w[0], w[1]);
    }
}

// =============================================================================
// AUTO MODEL PARITY
// =============================================================================

#[test]
fn auto_selects_on_exponential_data() {
    let values: Vec<f64> = (0..30)
        .map(|i| {
            let base = 10.0 * (0.08 * i as f64).exp();
            base + (i as f64 * 1.3).sin() * 0.5
        })
        .collect();
    let series = make_series(values);
    let result = auto::forecast_auto(&series, 5, 0.95).unwrap();

    println!("=== AUTO ON EXPONENTIAL DATA ===");
    for i in 0..5 {
        println!(
            "step {}: forecast={:.4}, lower={:.4}, upper={:.4}",
            i + 1, result.forecasts[i], result.lower_bounds[i], result.upper_bounds[i]
        );
    }

    assert_eq!(result.forecasts.len(), 5);
    for w in result.forecasts.windows(2) {
        assert!(w[1] > w[0], "Should increase for exponential data");
    }
}

#[test]
fn auto_handles_negatives() {
    let values: Vec<f64> = (0..20).map(|i| -10.0 + 2.0 * i as f64).collect();
    let series = make_series(values);
    let result = auto::forecast_auto(&series, 5, 0.95);
    assert!(result.is_ok(), "Auto should handle negative values");
    assert_eq!(result.unwrap().forecasts.len(), 5);
}

#[test]
fn auto_scurve_data() {
    let values: Vec<f64> = (0..40)
        .map(|i| 200.0 / (1.0 + (-0.2 * (i as f64 - 20.0)).exp()))
        .collect();
    let series = make_series(values);
    let result = auto::forecast_auto(&series, 5, 0.95).unwrap();

    println!("=== AUTO ON S-CURVE DATA ===");
    for i in 0..5 {
        println!(
            "step {}: forecast={:.4}, lower={:.4}, upper={:.4}",
            i + 1, result.forecasts[i], result.lower_bounds[i], result.upper_bounds[i]
        );
    }

    for fc in &result.forecasts {
        assert!(*fc < 250.0, "Should not overshoot capacity 200, got {:.2}", fc);
    }
}

// =============================================================================
// ETS MODEL PARITY
// =============================================================================

#[test]
fn ets_simple_trend() {
    let values: Vec<f64> = (0..20).map(|i| 10.0 + 2.0 * i as f64).collect();
    let series = make_series(values);
    let result = ets::forecast_ets(&series, 5, 0.95).unwrap();

    println!("=== ETS SIMPLE TREND ===");
    for i in 0..5 {
        let width = result.upper_bounds[i] - result.lower_bounds[i];
        println!(
            "step {}: forecast={:.4}, lower={:.4}, upper={:.4}, width={:.4}",
            i + 1, result.forecasts[i], result.lower_bounds[i], result.upper_bounds[i], width
        );
    }

    assert_eq!(result.forecasts.len(), 5);
    // ETS should produce increasing forecasts for upward trend
    for w in result.forecasts.windows(2) {
        assert!(w[1] > w[0], "ETS should forecast upward for upward trend");
    }
}

// =============================================================================
// DECELERATION DETECTION PARITY
// =============================================================================

// NOTE: shows_deceleration is pub(crate), tested internally in lib.rs tests

// =============================================================================
// SEASONALITY DETECTION PARITY
// =============================================================================

#[test]
fn seasonality_periodic_data() {
    // Clear 7-period seasonality
    let values: Vec<f64> = (0..56)
        .map(|i| {
            let trend = i as f64 * 0.5;
            let seasonal = 10.0 * (2.0 * std::f64::consts::PI * i as f64 / 7.0).sin();
            trend + seasonal + 50.0
        })
        .collect();
    let series = make_series(values);
    let results = detect_seasonality(&series.values).unwrap();

    println!("=== SEASONALITY DETECTION ===");
    for r in &results {
        println!("period={}, strength={:.4}", r.period, r.strength);
    }

    // Should detect period=7
    assert!(
        results.iter().any(|r| r.period == 7),
        "Should detect period 7, got: {:?}",
        results.iter().map(|r| r.period).collect::<Vec<_>>()
    );
}

// =============================================================================
// CROSS-MODEL CONSISTENCY
// =============================================================================

#[test]
fn all_models_produce_valid_output() {
    let values: Vec<f64> = (0..20)
        .map(|i| 100.0 + 5.0 * i as f64 + (i as f64 * 0.8).sin() * 3.0)
        .collect();
    let series = make_series(values);

    let models = vec![
        ("linear", ForecastModel::Linear),
        ("exponential", ForecastModel::Exponential),
        ("ets", ForecastModel::ETS),
        ("auto", ForecastModel::Auto),
    ];

    println!("=== ALL MODELS COMPARISON ===");
    for (name, model) in &models {
        let config = ForecastConfig {
            model: model.clone(),
            horizon: 5,
            confidence_level: 0.95,
        };
        let result = forecast(&series, &config).unwrap();

        println!("\n--- {} ---", name);
        for i in 0..5 {
            let width = result.upper_bounds[i] - result.lower_bounds[i];
            println!(
                "  step {}: forecast={:.2}, lower={:.2}, upper={:.2}, width={:.2}",
                i + 1, result.forecasts[i], result.lower_bounds[i], result.upper_bounds[i], width
            );
        }

        // Basic validity checks for all models
        assert_eq!(result.forecasts.len(), 5, "{} should produce 5 forecasts", name);
        assert_eq!(result.timestamps.len(), 5, "{} should produce 5 timestamps", name);
        for i in 0..5 {
            assert!(
                result.upper_bounds[i] >= result.lower_bounds[i],
                "{} step {}: upper {:.4} should be >= lower {:.4}",
                name, i + 1, result.upper_bounds[i], result.lower_bounds[i]
            );
            assert!(
                result.forecasts[i] >= result.lower_bounds[i],
                "{} step {}: forecast {:.4} should be >= lower {:.4}",
                name, i + 1, result.forecasts[i], result.lower_bounds[i]
            );
            assert!(
                result.forecasts[i] <= result.upper_bounds[i],
                "{} step {}: forecast {:.4} should be <= upper {:.4}",
                name, i + 1, result.forecasts[i], result.upper_bounds[i]
            );
            assert!(!result.forecasts[i].is_nan(), "{} forecast[{}] is NaN", name, i);
            assert!(!result.lower_bounds[i].is_nan(), "{} lower[{}] is NaN", name, i);
            assert!(!result.upper_bounds[i].is_nan(), "{} upper[{}] is NaN", name, i);
        }
    }
}

#[test]
fn bands_widen_all_models() {
    // Noisy data — bands should widen for all models that support prediction intervals
    let values = vec![
        22.1, 19.8, 24.5, 21.0, 26.3, 20.7, 23.9, 18.2,
        25.6, 22.4, 27.1, 19.5, 24.8, 21.3, 26.7, 20.1,
        23.4, 25.9, 18.7, 24.2,
    ];
    let series = make_series(values);

    println!("=== BAND WIDENING CHECK ===");

    // Linear should definitely widen
    let result = linear::forecast_linear(&series, 10, 0.95).unwrap();
    let widths: Vec<f64> = (0..10)
        .map(|i| result.upper_bounds[i] - result.lower_bounds[i])
        .collect();

    println!("Linear band widths: {:?}", widths.iter().map(|w| format!("{:.2}", w)).collect::<Vec<_>>());

    for w in widths.windows(2) {
        assert!(
            w[1] > w[0],
            "Linear bands must widen: {:.4} -> {:.4}",
            w[0], w[1]
        );
    }

    // Exponential should also widen
    // Need all positive values (already are)
    let result = exponential::forecast_exponential(&series, 10, 0.95).unwrap();
    let widths: Vec<f64> = (0..10)
        .map(|i| result.upper_bounds[i] - result.lower_bounds[i])
        .collect();

    println!("Exponential band widths: {:?}", widths.iter().map(|w| format!("{:.2}", w)).collect::<Vec<_>>());

    for w in widths.windows(2) {
        assert!(
            w[1] > w[0],
            "Exponential bands must widen: {:.4} -> {:.4}",
            w[0], w[1]
        );
    }
}

#[test]
fn timestamps_are_sequential() {
    let values: Vec<f64> = (0..15).map(|i| 100.0 + i as f64 * 3.0).collect();
    let series = make_series(values);
    let result = linear::forecast_linear(&series, 5, 0.95).unwrap();

    // Timestamps should continue from the last one
    let last_ts = 1000 + 14; // timestamps start at 1000, 15 values = last is 1014
    for i in 0..5 {
        assert_eq!(
            result.timestamps[i],
            last_ts + (i as i32 + 1),
            "Timestamp {} should be {}",
            i, last_ts + (i as i32 + 1)
        );
    }
}
