import { useEffect, useRef, useState } from 'react';
import type { ChartML } from '@chartml/core';

export interface ChartMLChartProps {
  /** ChartML YAML specification */
  spec: string;
  /** Pre-configured ChartML instance (from useChartML) */
  chartml: ChartML;
  /** Optional width override */
  width?: number;
  /** Optional height override */
  height?: number;
  /** CSS class for the container */
  className?: string;
  /** Inline styles for the container */
  style?: React.CSSProperties;
  /** Error callback */
  onError?: (error: Error) => void;
}

export function ChartMLChart({ spec, chartml, width, height, className, style, onError }: ChartMLChartProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<string | null>(null);

  // Track container width for responsive sizing
  const [containerWidth, setContainerWidth] = useState<number>(0);

  useEffect(() => {
    if (!containerRef.current) return;
    const observer = new ResizeObserver((entries) => {
      const entry = entries[0];
      if (entry) {
        setContainerWidth(entry.contentRect.width);
      }
    });
    observer.observe(containerRef.current);
    return () => observer.disconnect();
  }, []);

  // Render chart when spec, size, or chartml changes
  useEffect(() => {
    if (!spec || !chartml || containerWidth <= 0) return;

    try {
      const effectiveWidth = width ?? containerWidth;
      const effectiveHeight = height ?? Math.round(effectiveWidth * 0.5); // 2:1 default aspect ratio
      const result = chartml.renderToSvg(spec, { width: effectiveWidth, height: effectiveHeight });
      setSvg(result);
      setError(null);
    } catch (e) {
      const err = e instanceof Error ? e : new Error(String(e));
      setError(err.message);
      onError?.(err);
    }
  }, [spec, chartml, containerWidth, width, height, onError]);

  if (error) {
    return (
      <div className={className} style={{ ...style, color: '#dc3545', fontFamily: 'monospace', padding: '12px', background: '#fff5f5', border: '1px solid #dc3545', borderRadius: '4px' }}>
        Chart error: {error}
      </div>
    );
  }

  // Using dangerouslySetInnerHTML because the SVG is generated by our own
  // WASM renderer from a ChartML YAML spec — not from untrusted user input.
  return (
    <div
      ref={containerRef}
      className={className}
      style={{ position: 'relative', ...style }}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
