import { useMemo } from 'react';
import type MarkdownIt from 'markdown-it';
import type { ChartML } from '@chartml/core';
import { chartmlPlugin } from '@chartml/markdown-it';

export interface ChartMLMarkdownProps {
  /** Markdown content with optional ```chartml code blocks */
  content: string;
  /** Pre-configured ChartML instance */
  chartml: ChartML;
  /** A markdown-it instance to use as the renderer */
  markdownIt: MarkdownIt;
  /** Default chart width */
  chartWidth?: number;
  /** Default chart height */
  chartHeight?: number;
  /** CSS class for the markdown container */
  className?: string;
}

export function ChartMLMarkdown({
  content,
  chartml,
  markdownIt,
  chartWidth = 800,
  chartHeight = 400,
  className = 'chartml-markdown',
}: ChartMLMarkdownProps) {
  const html = useMemo(() => {
    // chartmlPlugin replaces md.renderer.rules.fence (assignment, not append),
    // so re-applying with new width/height is safe and picks up prop changes.
    markdownIt.use(chartmlPlugin, { chartml, width: chartWidth, height: chartHeight });
    return markdownIt.render(content);
  }, [content, chartml, markdownIt, chartWidth, chartHeight]);

  // Using dangerouslySetInnerHTML because markdown-it produces HTML strings.
  // The SVG content is generated by our own WASM renderer, not user input.
  return (
    <div
      className={className}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
