//! Phase 1 backward-compatibility guardrail for the theme hooks work.
//!
//! Renders every YAML spec under `tests/charts/` with `Theme::default()` and
//! asserts byte-for-byte equality against the baseline SVGs captured at
//! `crates/chartml-test-runner/snapshots/pre-theme-hooks/`.
//!
//! The baseline was generated by a fresh `chartml-test --batch` run at HEAD
//! on the feat/theme-hooks branch (not copied from `test-output/golden/`,
//! whose signed fixtures predate recent theme refactors). Every subsequent
//! phase must leave this test passing — any rendering change while using
//! `Theme::default()` is a regression.
//!
//! On mismatch, the actual SVG is written to
//! `target/backward-compat-diffs/<subdir>/<name>.svg` for inspection.

use std::fs;
use std::path::{Path, PathBuf};

use chartml_chart_cartesian::CartesianRenderer;
use chartml_chart_metric::MetricRenderer;
use chartml_chart_pie::PieRenderer;
use chartml_chart_scatter::ScatterRenderer;
use chartml_core::element::ChartElement;
use chartml_core::ChartML;
use chartml_render::element_to_svg;

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR points at crates/chartml-test-runner
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(Path::parent)
        .expect("workspace root")
        .to_path_buf()
}

fn specs_dir() -> PathBuf {
    workspace_root().join("tests/charts")
}

fn snapshot_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("snapshots/pre-theme-hooks")
}

fn diff_dir() -> PathBuf {
    workspace_root().join("target/backward-compat-diffs")
}

fn create_chartml() -> ChartML {
    let mut c = ChartML::new();
    c.register_renderer("bar", CartesianRenderer::new());
    c.register_renderer("line", CartesianRenderer::new());
    c.register_renderer("area", CartesianRenderer::new());
    c.register_renderer("pie", PieRenderer::new());
    c.register_renderer("doughnut", PieRenderer::new());
    c.register_renderer("scatter", ScatterRenderer::new());
    c.register_renderer("bubble", ScatterRenderer::new());
    c.register_renderer("metric", MetricRenderer::new());
    c
}

fn collect_yamls(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let p = entry.path();
        if p.is_dir() {
            collect_yamls(&p, out);
        } else if p.extension().map(|e| e == "yaml" || e == "yml").unwrap_or(false) {
            out.push(p);
        }
    }
}

fn extract_dimensions(element: &ChartElement) -> (f64, f64) {
    match element {
        ChartElement::Svg {
            width,
            height,
            viewbox,
            ..
        } => (
            width.unwrap_or(viewbox.width),
            height.unwrap_or(viewbox.height),
        ),
        _ => (800.0, 400.0),
    }
}

struct Mismatch {
    spec: String,
    reason: String,
}

#[test]
fn backward_compat_goldens_byte_identical() {
    let specs_root = specs_dir();
    let snap_root = snapshot_dir();

    assert!(
        specs_root.is_dir(),
        "specs dir missing: {}",
        specs_root.display()
    );
    assert!(
        snap_root.is_dir(),
        "snapshot dir missing: {}",
        snap_root.display()
    );

    let mut yamls = Vec::new();
    collect_yamls(&specs_root, &mut yamls);
    yamls.sort();
    assert!(!yamls.is_empty(), "no yaml specs discovered");

    let chartml = create_chartml();
    let mut mismatches: Vec<Mismatch> = Vec::new();
    let mut compared = 0usize;
    let mut skipped_expect_error = 0usize;

    for yaml_path in &yamls {
        let rel = yaml_path.strip_prefix(&specs_root).unwrap();
        let chart_type = rel
            .parent()
            .map(|p| p.to_string_lossy().to_string())
            .unwrap_or_default();
        let stem = rel.file_stem().unwrap().to_string_lossy().to_string();
        let spec_id = if chart_type.is_empty() {
            stem.clone()
        } else {
            format!("{}/{}", chart_type, stem)
        };

        let yaml_text = match fs::read_to_string(yaml_path) {
            Ok(s) => s,
            Err(e) => {
                mismatches.push(Mismatch {
                    spec: spec_id,
                    reason: format!("read yaml failed: {}", e),
                });
                continue;
            }
        };

        let spec: serde_yaml::Value = match serde_yaml::from_str(&yaml_text) {
            Ok(v) => v,
            Err(e) => {
                mismatches.push(Mismatch {
                    spec: spec_id,
                    reason: format!("parse yaml failed: {}", e),
                });
                continue;
            }
        };

        let expect_error = spec
            .get("assertions")
            .and_then(|a| a.get("expect_error"))
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        if expect_error {
            skipped_expect_error += 1;
            continue;
        }

        let chart_value = match spec.get("chart") {
            Some(v) => v,
            None => {
                mismatches.push(Mismatch {
                    spec: spec_id,
                    reason: "missing `chart` key in test spec".into(),
                });
                continue;
            }
        };
        let chart_yaml = match serde_yaml::to_string(chart_value) {
            Ok(s) => s,
            Err(e) => {
                mismatches.push(Mismatch {
                    spec: spec_id,
                    reason: format!("re-serialize chart yaml failed: {}", e),
                });
                continue;
            }
        };

        let element = match chartml.render_from_yaml(&chart_yaml) {
            Ok(el) => el,
            Err(e) => {
                mismatches.push(Mismatch {
                    spec: spec_id,
                    reason: format!("render failed: {}", e),
                });
                continue;
            }
        };
        let (w, h) = extract_dimensions(&element);
        let actual_svg = element_to_svg(&element, w, h);

        let baseline_path = snap_root.join(&chart_type).join(format!("{}.svg", stem));
        let baseline = match fs::read_to_string(&baseline_path) {
            Ok(s) => s,
            Err(e) => {
                mismatches.push(Mismatch {
                    spec: spec_id,
                    reason: format!(
                        "baseline missing at {}: {}",
                        baseline_path.display(),
                        e
                    ),
                });
                continue;
            }
        };

        compared += 1;

        if actual_svg != baseline {
            // Persist actual for inspection
            let out_path = diff_dir().join(&chart_type).join(format!("{}.svg", stem));
            if let Some(parent) = out_path.parent() {
                let _ = fs::create_dir_all(parent);
            }
            let _ = fs::write(&out_path, &actual_svg);
            mismatches.push(Mismatch {
                spec: spec_id,
                reason: format!(
                    "byte mismatch (actual written to {})",
                    out_path.display()
                ),
            });
        }
    }

    if !mismatches.is_empty() {
        let mut msg = format!(
            "backward-compat: {} mismatches out of {} compared ({} expect_error skipped)\n",
            mismatches.len(),
            compared,
            skipped_expect_error
        );
        for m in &mismatches {
            msg.push_str(&format!("  - {}: {}\n", m.spec, m.reason));
        }
        panic!("{}", msg);
    }

    assert!(compared > 0, "no specs compared");
    println!(
        "backward_compat: {} specs byte-identical ({} expect_error skipped)",
        compared, skipped_expect_error
    );
}
